### ISSUE TITLE
sim.launch

### ISSUE THREAD

**Issue by garyedwards** [ipa320/ipa_seminar#24]
Hi due to restructuring in the "cob_robots" package I think the sim.launch file needs updating from:

pkg="cob_controller_configuration_gazebo" -> pkg="pr2_controller_manager"

Also the ur model renders a bit weird in gazebo but I have not looked into this yet.

![2014-03-29-141439_1600x900_scrot](https://cloud.githubusercontent.com/assets/122412/2558508/e1482ffe-b74c-11e3-9687-2b89d50fd9d8.png)

**Comment by fmessmer** [comment]
The rendering problem with the UR is known. The mesh looks right in RViz, though.

ipa_seminar has not yet been (fully) updated for using the new structure of cob_robots and other stacks. This is probably postponed until the new structure is officially released into debs.

What has been cob_controller_configuration_gazebo/ros/launch/controller_manager.launch has now moved to cob_controller_configuration_gazebo/launch/components/controller_manager.launch. As to the `spawner`: yes, the spawner in pr2_controller_manager package can be used.

**Comment by floweisshardt** [comment]
done for October '15 training
